services:
  db:
    profiles: ["postgres"]
    ports:
      - "${DB_PORT:-5432}:5432"

  backend:
    build:
      target: dev
    environment:
      DEBUG: 1
      DB_ENGINE: ${DB_ENGINE:-sqlite}
      DATABASE_URL: ${DB_ENGINE}://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./server:/app

  frontend:
    build:
      target: dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    volumes:
      - ./client:/app
      - /app/node_modules