# Generated by Django 5.2.4 on 2025-08-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='answer',
        ),
    ]
