# Generated by Django 5.2.4 on 2025-08-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_remove_chatmessage_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
