# Generated by Django 5.2.4 on 2025-08-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_chat_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='likes',
        ),
    ]
