# Generated by Django 5.2.4 on 2025-09-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_remove_chatmessage_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
