# Generated by Django 5.2.4 on 2025-09-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_chatmessage_options_alter_chatmessage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/chats/'),
        ),
        migrations.AddField(
            model_name='chat',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
