# Generated by Django 5.2.4 on 2025-09-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_chat_photo_chat_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
